name: CloudStorage
main: net.aerulion.cloudstorage.Main
version: '1.1'
api-version: '1.16'
depend: [ Nucleus, Vault, WorldGuard ]
author: aerulion
commands:
  cloudstorage:
    description: Main command
    aliases: [ cloud ]
permissions:
  cloudstorage.buy.cloudaccesspoint:
    default: op
  cloudstorage.buy.cloudinterface:
    default: op
  cloudstorage.buy.cloudstorageslot:
    default: op
  cloudstorage.buy.upgrade:
    default: op
  cloudstorage.buy.wirelesscloudaccesspoint:
    default: op
  cloudstorage.buy.wirelesscloudinterface:
    default: op
  cloudstorage.bypass.gamemode:
    default: op
  cloudstorage.bypass.private:
    default: op
  cloudstorage.bypass.world:
    default: op
  cloudstorage.cmd.deleteplayerdata:
    default: op
  cloudstorage.cmd.interface:
    default: op
  cloudstorage.cmd.itemcache:
    default: op
  cloudstorage.cmd.list:
    default: op
  cloudstorage.cmd.maintenancemode:
    default: op
  cloudstorage.cmd.reload:
    default: op
  cloudstorage.cmd.reencodeitems:
    default: op
  cloudstorage.cmd.stats:
    default: op