name: CloudStorage
main: net.aerulion.cloudstorage.Main
version: '1.0'
api-version: '1.16'
depend: [ Nucleus, Vault, WorldGuard ]
author: aerulion
commands:
  cloudstorage:
    description: Main command
    aliases: [ cloud ]
permissions:
  buy.cloudaccesspoint:
    default: op
  buy.cloudinterface:
    default: op
  buy.cloudstorageslot:
    default: op
  buy.upgrade:
    default: op
  buy.wirelesscloudaccesspoint:
    default: op
  buy.wirelesscloudinterface:
    default: op
  bypass.private:
    default: op
  cmd.deleteplayerdata:
    default: op
  cmd.interface:
    default: op
  cmd.itemcache:
    default: op
  cmd.list:
    default: op
  cmd.stats:
    default: op